package com.ainnect.common.enums;

public enum ActivityAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_LOCKED,
    USER_UNLOCKED,
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_REPORTED,
    COMMENT_CREATED,
    COMMENT_DELETED,
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    REPORT_CREATED,
    REPORT_RESOLVED,
    ADMIN_ACTION
}


